name: holaMundo

on:
   push:
      branches:
        - main
        - developer
        - releases
        - hotfix
jobs: 
   Saludos:
     runs-on: ubuntu-latest

     steps:
       - name: descargar el repo
         uses: actions/checkout@v4

       - name: hola Push
         run: echo "hola mundo desde githun actions on push"
